--- # this is to install java and Jenkins on the hosts
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:
    - name: Install Java on RedHat
      yum:
        name: java
        state: present
      when: ansible_os_family == 'RedHat'
    - name: Install java on Debain
      apt:
        name: openjdk-6-jdk
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: Download Jenkins packages
      get_url:
         url: https://pkg.jenkins.io/redhat/jenkins.repo
         dest: /etc/yum.repos.d/jenkins.repo
    - name: Downlad key for the jenkins rpm module
      rpm_key:
         state: present
         key: https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: Install Jenkins on the Redhat
      action: yum name=jenkins state=present

    - name: Start the Jenkins services
      service:
        name: jenkins
        state: started
        enabled: yes
